# Generated by Django 3.2.5 on 2023-07-12 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Q1', models.CharField(choices=[('Strongly Agree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neither Agree or Disagree', 'Neither Agree or Disagree'), ('Disagree', 'Disagree'), ('Strongly Disagree', 'Strongly Disagree')], default='Neither Agree or Disagree', max_length=25)),
                ('Q2', models.CharField(choices=[('Strongly Agree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neither Agree or Disagree', 'Neither Agree or Disagree'), ('Disagree', 'Disagree'), ('Strongly Disagree', 'Strongly Disagree')], default='Neither Agree or Disagree', max_length=25)),
                ('Q3', models.CharField(choices=[('Strongly Agree', 'Strongly Agree'), ('Agree', 'Agree'), ('Neither Agree or Disagree', 'Neither Agree or Disagree'), ('Disagree', 'Disagree'), ('Strongly Disagree', 'Strongly Disagree')], default='Neither Agree or Disagree', max_length=25)),
            ],
            options={
                'ordering': ['Q1', 'Q2', 'Q3'],
            },
        ),
    ]
